### ISSUE TITLE
Some background Information about the tools

### ISSUE THREAD

**Issue by Schizo** [hungptit/tools#2]
First of all thanks for this repo, this might be really useful for big data collections. 
I was wondering if we could put links to the projects some of the tools are pulled from, for example `mupdatedb`. I was wondering if that tool is threaded?

**Comment by hungptit** [comment]
@Schizo mupdatedb is single threaded. I have not tried to parallelize it since it is very hard to create efficient algorithms for unknown inputs. If you know the structure of your folders then you can generate file information databases in parallel and combine them later using **cat** command. Below is a simple example that works on my machine.
``` shell
mupdatedb /Users/hdang/working/ioutils/ -d db1 &
mupdatedb /Users/hdang/working/utils/ -d db2
cat db1 >> .database
cat db2 >> .database
```

BTW. I have updated references for mupdate, mlocate, and mfind commands.

**Comment by hungptit** [comment]
Or you can generate several database files and use them to locate your files
``` shell
mlocate -d db1.db -d db2.db '(mlocate|mfind)[.](c|h)pp'
../src/mlocate.hpp
../benchmark/mfind.cpp
../benchmark/CMakeFiles/mfind.dir/mfind.cpp.o
../src/mlocate.hpp
../benchmark/mfind.cpp
../benchmark/CMakeFiles/mfind.dir/mfind.cpp.o
```

**Comment by hungptit** [comment]
@Schizo I am going to close this issue. Please let me know if you have any question or suggestion related to fast-locate and fast-updatedb.

**Comment by Schizo** [comment]
@hungptit  Thanks for that! That explains a lot.
